version: '3.8'

networks:
  public:
    name: public
    external: true

services:

    train_tune:
        deploy:
          replicas: 1
        image: 'registry.rubercubic.com:5001/a3c-orderbook'
        volumes:
            - ${HOME}/.exchange-data/:/home/joliveros/.exchange-data/
        command: bash -c "source ~/.bashrc && 
          ./A3C/A3C_Discrete.py --update_interval 10 --num_workers 3 \
          --batch_size 3 --max_episodes 7"
        environment:
            - LOG_LEVEL=DEBUG
            - CUDA_VISIBLE_DEVICES=0
        networks:
            - public
        depends_on:
            - influxdb
            - redis
        secrets:
            - DB
            - KERAS_DB
            - WANDB_API_KEY


secrets:
  DB:
    external: true
  KERAS_DB:
    external: true
  WANDB_API_KEY:
    external: true
